### ISSUE TITLE
关于erc20标准的确立

### ISSUE THREAD

**Issue by LBJyang** [WTFAcademy/WTF-Ethers#101]
ERC20Check中的这段话：ERC20标准中只有 transfer(address, uint256) 不包含在 ERC721标准、ERC1155和ERC777标准中。因此如果一个合约包含 transfer(address, uint256) 的选择器，就能确定它是 ERC20 代币合约，而不是其他。
以太坊区块链上的合约有那么多，任何人都可以部署任何合约上去，不能说排除了721/1155/777之外就可以吧，任何其他非erc20合约只要包含transfer(address, uint256) 函数完全有可能，甚至可能是恶意的。这个说法能成立吗？

**Comment by AmazingAng** [comment]
的确不够严谨。这里是说区分ERC20和其他标准（ERC721, ERC1155, ERC777）。
如果严谨的话，就要把ERC20标准的6个选择器都放上去。
恶意的没关系，因为任何人都能部署erc20，没有动机用其他合约伪造erc20。这只是一个初筛的方法。

**Comment by LBJyang** [comment]
好的。
