### ISSUE TITLE
ethers 第十五课，跑了好几篇，都报错，有知道什么原因么？

### ISSUE THREAD

**Issue by zhanggui1024** [WTFAcademy/WTF-Ethers#38]
var error = new Error(message);
                    ^

Error: missing response (requestBody="{\"method\":\"eth_getBalance\",\"params\":[\"0x74777aa4d53dea221d77227d11dbbaf04d5459bd\",\"latest\"],\"id\":47,\"jsonrpc\":\"2.0\"}", requestMethod="POST", serverError={"errno":-4077,"code":"ECONNRESET","syscall":"read"}, url="https://eth-goerli.alchemyapi.io/v2/GlaeWuylnNM3uuOo-SAwJxuwTdqHaY5l", code=SERVER_ERROR, version=web/5.7.1)

reason: 'missing response',
  code: 'SERVER_ERROR',
  requestBody: '{"method":"eth_getBalance","params":["0x74777aa4d53dea221d77227d11dbbaf04d5459bd","latest"],"id":47,"jsonrpc":"2.0"}',
  requestMethod: 'POST',
  serverError: Error: read ECONNRESET
      at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20) {
    errno: -4077,
    code: 'ECONNRESET',
    syscall: 'read'
  },
  url: 'https://eth-goerli.alchemyapi.io/v2/GlaeWuylnNM3uuOo-SAwJxuwTdqHaY5l'

**Comment by AmazingAng** [comment]
网卡了？

**Comment by luoluo3310** [comment]
const iface = new utils.Interface([
    "function exactInputSingle(tuple(address tokenIn, address tokenOut, uint24 fee, address recipient, uint deadline, uint amountIn, uint amountOutMinimum, uint160 sqrtPriceLimitX96) calldata) external payable returns (uint amountOut)",
])
里面的new utils.Interface是不是要改成new ethers.utils.Interface
