### ISSUE TITLE
Uncaught SyntaxError: Cannot use import statement outside a module"

### ISSUE THREAD

**Issue by oooomoooo** [WTFAcademy/WTF-Ethers#42]
报错Uncaught SyntaxError: Cannot use import statement outside a module"
或者 SyntaxError: The requested module 'ethers' does not provide an export named 'ethers'
就是这两个报错，请大神帮忙，怎么才能运行起来，因为这一课没法用那个在线编辑器，已经半天了还是运行不起来，求大神帮帮我
![)JMQCII X04D2Q}M3UFBL@O](https://user-images.githubusercontent.com/92239221/201478035-568406c4-af23-4012-a22f-f1608d008cd9.png)

**Comment by greyhao** [comment]
以下两种方式均可以正常运行
方法 1, 在 `package.json`  中添加  `"type": "module"`
方法 2, 使用 `const ethers = require('ethers')` 而非 `import` 
选择其中一种即可

**Comment by AmazingAng** [comment]
应该是js/es版本问题，没有更新到最新。可以参考楼上的引用方法。
