### ISSUE TITLE
对比数据格式不同，无法触发

### ISSUE THREAD

**Issue by 0x621e** [WTFAcademy/WTF-Ethers#44]
https://github.com/WTFAcademy/WTF-Ethers/blob/0a7ff6526ac07be961b47e3a1877870c28303a82/16_MultiCollect/MultiCollect.js#L58

应为：
  if (
    ethers.utils.formatEther(balanceETH) > ethers.utils.formatEther(amount) &&
    ethers.utils.formatEther(balanceWETH) >= ethers.utils.formatEther(amount)
  )

**Comment by AmazingAng** [comment]
感谢指出 提个pr吧

**Comment by 0x621e** [comment]
pr merged
