### ISSUE TITLE
await outside async

### ISSUE THREAD

**Issue by w-zhong** [WTFAcademy/WTF-Ethers#46]
https://github.com/WTFAcademy/WTF-Ethers/blob/c4a23920fd42fd0a41dee5b96c19c04544446dea/18_Signature/Signature.js#L33

此处的await没有包在 async main 中，报错

![截屏2022-11-29 16 09 28](https://user-images.githubusercontent.com/99269419/204473926-f254f363-dc04-49f9-a424-7df400b645ae.png)

**Comment by AmazingAng** [comment]
的确 你提个pr吧

**Comment by AmazingAng** [comment]
我的确可以运行，但这不是标准写法，会改一下。
见 top-level await: https://opensource.com/article/20/11/top-level-await-javascript#:~:text=Top%2Dlevel%20await%20is%20supported,has%20been%20added%20in%20Node.
