### ISSUE TITLE
24_ERC20Check 中，balanceOf(address)的选择器ID疑似有误

### ISSUE THREAD

**Issue by lurengeng** [WTFAcademy/WTF-Ethers#68]
教程及其代码里说balanceOf(address)的选择器ID是  18160ddd

但本人测试，应为70a08231

请查阅，谢谢

![image](https://user-images.githubusercontent.com/61215384/231714769-1c3ecbbe-b3fe-4aad-bd5f-5a67eee71552.png)

**Comment by AmazingAng** [comment]
感谢反馈，18160ddd 是 totalSupply() 的 selector，已经改正
