### ISSUE TITLE
教程9 输出问题

### ISSUE THREAD

**Issue by cjh20000613** [WTFAcademy/WTF-Ethers#91]
![image](https://github.com/WTFAcademy/WTF-Ethers/assets/65795263/771e193a-e3ee-40ad-baa5-7ffc59b11b94)
为什么会出现这样输出
教程8里的输出没有问题
![image](https://github.com/WTFAcademy/WTF-Ethers/assets/65795263/b0a4c3d3-77d1-4300-8f66-098778b704a8)

**Comment by cjh20000613** [comment]
而且我使用v5时输出也没问题，把ethers.js换成6.3.0，修改代码后就出现输出问题

**Comment by AmazingAng** [comment]
已经修改好了 请使用新的代吗
